[package]
name = "ctex"
version = "0.2.0"
authors = ["Sean Moulton <bananamoulton@gmail.com>"]
edition = "2018"

[dependencies]
lz4 = "1.23.2"
anyhow = "1.0.40"
glob = "0.3.0"
image = "0.23.14"
num-integer = "0.1.44"