[package]
name = "ctex"
version = "0.2.0"
authors = ["Sean Moulton <bananamoulton@gmail.com>"]
edition = "2018"

[dependencies]
lz4_flex = "0.7.5"
anyhow = "1.0.40"
image = { version = "0.23.14" }
num-integer = { version = "0.1.44" }
glob = { version = "0.3.0" }