[package]
name = "ctex_tools"
version = "0.1.0"
authors = ["Sean Moulton <bananamoulton@gmail.com>"]
edition = "2018"

[dependencies]
ctex = { git = "https://github.com/WindowsVista42/ctex_image", features = ["par_util"] }
